<template>
  <hr>
  <br>
  <div>
    <h4><span class="font-weight-bold">Step 1:</span> URL Generation</h4>
    <p>The URL for Webhook is generated by system.</p>
    <p>You may attach the below URL onto Github for Webhook notification.</p>
    <div class="custom-box">
      <p>{{ webhookUrl }}</p>
    </div>

    <div class="space-x-2 mb-4">
      <button @click="generateWebhookUrl" class="bg-white-500 hover:bg-white-700 text-pink font-bold py-1 px-1 rounded">
        Refresh URL
      </button>
      <button @click="copyUrl" class="bg-white-500 hover:bg-white-700 text-pink font-bold py-1 px-1 rounded">
        Copy URL
      </button>
    </div>
    <div class="space-x-2 mb-4">
      <button @click="next" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
        Next
      </button>
    </div>
    <div v-if="showNotification" class="notification">URL copied to clipboard!</div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  data() {
    return {
      webhookUrl: '',
      showNotification: false
    };
  },
  created() {
    this.generateWebhookUrl();
  },
  methods: {
    generateWebhookUrl() {
      let baseURLdynamic = window.location.href.includes('localhost')
        ? 'http://localhost:3000/webhook'
        : 'http://54.199.209.19/webhook'
      const uniqueId = this.generateUniqueId();
      this.webhookUrl = `${baseURLdynamic}/${uniqueId}`;
    },
    generateUniqueId(): string {
      return 'xxxx-xxxx-xxxx-xxxx'.replace(/[x]/g, () => {
        return (Math.random() * 16 | 0).toString(16);
      });
    },
    copyUrl() {
      navigator.clipboard.writeText(this.webhookUrl).then(() => {
        this.showNotification = true;
        setTimeout(() => {
          this.showNotification = false;
        }, 3000);
      }).catch(err => {
        console.error('Failed to copy URL: ', err);
      });
    },
    next() {
      this.$emit('next', { url: this.webhookUrl });
    }
  }
});
</script>

<style lang="scss" scoped>
@import '@/assets/styles.scss';

.custom-box {
  @apply bg-gray-100 p-4 rounded-lg;
  border: 1px solid $gray-2;
}

.custom-link {
  color: $accent-color;

  &:hover {
    text-decoration: underline;
  }
}

.responsive-text {
  font-size: 1rem;

  @include responsive(small) {
    font-size: 1.2rem;
  }

  @include responsive(medium) {
    font-size: 1.4rem;
  }

  @include responsive(large) {
    font-size: 1.6rem;
  }

  @include responsive(xlarge) {
    font-size: 1.8rem;
  }

  @include responsive(xxlarge) {
    font-size: 2rem;
  }
}

.bg-primary-color {
  background-color: $primary-color;
}

.bg-secondary-color {
  background-color: $secondary-color;
}

.bg-accent-color {
  background-color: $accent-color;
}

.bg-gray-1 {
  background-color: $gray-1;
}

.bg-gray-2 {
  background-color: $gray-2;
}

.bg-brown-1 {
  background-color: $brown-1;
}

.bg-pink-red-1 {
  background-color: $pink-red-1;
}

.bg-red-1 {
  background-color: $red-1;
}

.color-white {
  color: $vt-c-white;
}

.notification {
  position: fixed;
  left: 50%;
  background-color: #ef5350;
  color: white;
  padding: 10px 20px;
  border-radius: 5px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
  opacity: 1;
  transition: opacity 0.5s ease-in-out;
}

.notification.hidden {
  opacity: 0;
}
</style>